//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearSpace.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearSpace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the export folder.
        /// </summary>
        public static string CLEANAPACE_OPENPHOTOFOLDER {
            get {
                return ResourceManager.GetString("CLEANAPACE_OPENPHOTOFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoShifter.
        /// </summary>
        public static string CLEANSPACE_APPNAME {
            get {
                return ResourceManager.GetString("CLEANSPACE_APPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring {0} files.
        /// </summary>
        public static string CLEANSPACE_TRANSFER_STATUS {
            get {
                return ResourceManager.GetString("CLEANSPACE_TRANSFER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0}.
        /// </summary>
        public static string CLEANSPACE_TRANSFER_STATUS2 {
            get {
                return ResourceManager.GetString("CLEANSPACE_TRANSFER_STATUS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End the transfer and resume network connection..
        /// </summary>
        public static string CS_AGRESSIVESTOP {
            get {
                return ResourceManager.GetString("CS_AGRESSIVESTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring files. Are you sure to end the transfer and exit?.
        /// </summary>
        public static string CS_CONFIRM_QUIT {
            get {
                return ResourceManager.GetString("CS_CONFIRM_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CS_CURRENT_NETWORK {
            get {
                return ResourceManager.GetString("CS_CURRENT_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To improve transfer experience, your PC has been connected to the mobile hotspot. After the transfer, your previous network connection will resume automatically..
        /// </summary>
        public static string CS_NETSWITCH_CONTENT {
            get {
                return ResourceManager.GetString("CS_NETSWITCH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string CS_NETSWITCH_TITLE {
            get {
                return ResourceManager.GetString("CS_NETSWITCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available, update now?.
        /// </summary>
        public static string CS_NEW_VER_AVAILABLE {
            get {
                return ResourceManager.GetString("CS_NEW_VER_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CS_NO {
            get {
                return ResourceManager.GetString("CS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network.
        /// </summary>
        public static string CS_NO_NETWORK {
            get {
                return ResourceManager.GetString("CS_NO_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to phone. You can view the previously exported files..
        /// </summary>
        public static string CS_NOCONN_TIP {
            get {
                return ResourceManager.GetString("CS_NOCONN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string CS_NOUN_COMPUTER {
            get {
                return ResourceManager.GetString("CS_NOUN_COMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official webSite: .
        /// </summary>
        public static string CS_OFFICIAL_WEBSITE {
            get {
                return ResourceManager.GetString("CS_OFFICIAL_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string CS_PC_READY {
            get {
                return ResourceManager.GetString("CS_PC_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving.
        /// </summary>
        public static string CS_PC_RECEIVING {
            get {
                return ResourceManager.GetString("CS_PC_RECEIVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please operate on your phone.
        /// </summary>
        public static string CS_PLS_WORK_ON_PHONE {
            get {
                return ResourceManager.GetString("CS_PLS_WORK_ON_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect to this PC on your phone.
        /// </summary>
        public static string CS_PlSCONNFROMMOBILE {
            get {
                return ResourceManager.GetString("CS_PlSCONNFROMMOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR code to download.
        /// </summary>
        public static string CS_SCAN_QR_CODE_DOWNLOAD1 {
            get {
                return ResourceManager.GetString("CS_SCAN_QR_CODE_DOWNLOAD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoShifter (mobile version).
        /// </summary>
        public static string CS_SCAN_QR_CODE_DOWNLOAD2 {
            get {
                return ResourceManager.GetString("CS_SCAN_QR_CODE_DOWNLOAD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total transferred {0} files.
        /// </summary>
        public static string CS_TRANS_COMPLETE_RESULT {
            get {
                return ResourceManager.GetString("CS_TRANS_COMPLETE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CS_TRANS_COMPLETE_STATUS {
            get {
                return ResourceManager.GetString("CS_TRANS_COMPLETE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to receive….
        /// </summary>
        public static string CS_TRANS_PREPARING {
            get {
                return ResourceManager.GetString("CS_TRANS_PREPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CS_YES {
            get {
                return ResourceManager.GetString("CS_YES", resourceCulture);
            }
        }
    }
}
