// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;
import com.microsoft.onedriveaccess.ODConnection;

import java.util.Date;
import java.util.List;

public class UploadSession {
	
	private static final String UP_URL = ODConnection.BASE_URL + "/up/";
	
   @SerializedName("uploadUrl")
   public String UploadUrl;
   @SerializedName("expirationDateTime")
   public Date ExpirationDateTime;
   @SerializedName("nextExpectedRanges")
   public List<String> NextExpectedRanges;

   public String getUploadSession() {
	   String uploadSession = "";
	   if(UploadUrl.startsWith(UP_URL)) {
		   uploadSession = UploadUrl.substring(UP_URL.length());
	   }
	   return uploadSession;
   }
}
